# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc3665ba34980964ecd1f03643157aff1fa47859abe1dc08fa4cfcfb6431d97bfeca20510e4877243c50ee44d765428629c5446a742f8c8d7dd42ed9e56b874a

test:
  secret_key_base: 0213d68bce23c60ad6a26772ca359a88dbe28d4e42534a775d5877fd83de9fee92c7fb01e5791c16b1b6b6c35619c70e21530dce5cb77d843925c9358cf6a545

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
